### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by birdbrainswagtrain** [thegrb93/gmodphysgunlimiter#2]
Sorry if this is a stupid way to contact you. I was going through my old files and found a copy of physgun buildmode. I didn't go through to code too thoroughly, but I thought it might be useful to you, depending on what features you want to add to this.

https://gist.github.com/birdbrainswagtrain/e5477117869e220a3388

**Comment by thegrb93** [comment]
It has a lot of helpful things for building, but I think it should stay separate from this since this adds limitations on the physgun rather than helps with building. Thanks for the offer though. Here's the updated physgun-buildmode http://facepunch.com/showthread.php?t=1239976
